// Character select: preselected hero, picking swaps the model + shows off, idle flourish, a still camera (no orbit),
// then the pet step: every pet, the pet framed beside the hero, locked ones say how to find them, per-hero memory.
import './lib/setup.mjs';
const G = new URL('../../src/', import.meta.url).href;
{ const qs = document.querySelector, menu = qs();
  menu._all = ['play', 'settings', 'controls', 'credits'].map(act => { const b = document.createElement('button'); b.dataset.act = act; return b; });
  document.querySelector = sel => (sel === '#title .tmenu' ? menu : qs(sel)); }
const { Game } = await import(G + 'core/Game.js');
const { MainMenu } = await import(G + 'ui/MainMenu.js');
const { CharacterSelect } = await import(G + 'ui/CharacterSelect.js');
const { Pets } = await import(G + 'gameplay/Pets.js');
const { ctx } = await import(G + 'core/context.js');
const { dom } = await import(G + 'ui/dom.js');
const { cam } = await import(G + 'systems/CameraSystem.js');
const { camera } = await import(G + 'render/scene.js');
const game = new Game(); game.init();
const step = s => { for (let i = 0; i < s * 60; i++) { game.update(1 / 60); game.renderSystem.render(); } };
let fails = 0; const check = (ok, m) => { console.log(`${ok ? 'PASS' : 'FAIL'}  ${m}`); if (!ok) fails++; };
const still = secs => { const p0 = camera.position.clone(); step(secs); return camera.position.distanceTo(p0); };
step(1); MainMenu.play(); step(0.2);
check(CharacterSelect.choice === ctx.player.charId && CharacterSelect.step === 'hero', `opens on the hero step with the current hero picked (${CharacterSelect.choice})`);
check(dom.heroDetail.innerHTML.includes('Ranged caster') && dom.heroDetail.innerHTML.includes('Meteor'), 'detail panel shows role and abilities');
const root0 = ctx.player.root;
CharacterSelect.pick('knight'); step(0.05);
check(ctx.player.charId === 'knight' && ctx.player.root !== root0, 'picking swaps the hero model');
check(ctx.player.spinT > 0 && !ctx.player.grounded, 'and the hero shows off (axe spin + hop)');
check(dom.heroDetail.innerHTML.includes('Melee bruiser') && dom.heroDetail.innerHTML.includes('Leap Slam'), 'detail panel follows the pick');
step(1); ctx.player.spinT = 0; ctx.player.castT = 0; step(6);
check(ctx.player.spinT > 0 || CharacterSelect.showT > 0, 'idle flourish after a few seconds');
step(3); const heroMove = still(4);
check(heroMove < 0.02, `the camera holds still on the hero, no orbit (moved ${heroMove.toFixed(3)} in 4 s)`);
const hd = camera.position.distanceTo(ctx.player.pos.clone().addScaledVector(ctx.player.up, 1.05));
check(Math.abs(hd - 4.6) < 0.3, `close, fixed framing on the hero (${hd.toFixed(2)} m)`);
check(dom.go.textContent.includes('pet'), `the button leads on to the pet (${dom.go.textContent.trim()})`);
CharacterSelect.key('Enter');
check(CharacterSelect.step === 'pet' && !ctx.started && dom.start.classList.contains('petstep'), 'Enter: on to the pet step (not into the game yet)');
check(dom.selHead.textContent === 'Choose your pet', 'heading says so');
const cards = dom.petCards.innerHTML;
check((cards.match(/data-pet=/g) || []).length === 6 && (cards.match(/ locked/g) || []).length === 4, 'every pet is listed; the four still to find are locked');
check(CharacterSelect.petView === 'wolf' && dom.petDetail.innerHTML.includes('Howl') && dom.petDetail.innerHTML.includes('health'), "the knight's own wolf is picked, with its stats and ability");
step(3); const pd = camera.position.distanceTo(ctx.companion.pos); const petMove = still(3);
check(pd < 4 && petMove < 0.05, `the camera frames the pet, still (${pd.toFixed(2)} m away, moved ${petMove.toFixed(3)})`);
CharacterSelect.key('ArrowRight');
check(CharacterSelect.petView === 'fox' && Pets.id === 'wolf' && dom.petDetail.innerHTML.includes('How to find them'), 'a locked pet shows how to find it, and stays home');
CharacterSelect.key('ArrowLeft'); CharacterSelect.key('ArrowLeft');
check(CharacterSelect.petView === 'owl' && Pets.id === 'owl' && ctx.companion.petId === 'owl', 'picking the owl brings it out beside the hero');
step(3); const od = camera.position.distanceTo(ctx.companion.pos);
check(od < 4.2, `and the camera moves to it (${od.toFixed(2)} m)`);
check(dom.go.textContent.includes('Boy Warrior') && dom.go.textContent.includes('Pip'), `Play button names both (${dom.go.textContent.trim()})`);
MainMenu.key('Escape'); check(CharacterSelect.step === 'hero' && MainMenu.screen === 'select', 'Esc goes back to the hero step first');
CharacterSelect.pick('ranger'); check(Pets.id === 'owl', "the ranger's own owl");
CharacterSelect.key('Enter'); CharacterSelect.key('ArrowRight');
check(Pets.id === 'wolf', 'the ranger takes the wolf');
MainMenu.key('Escape'); CharacterSelect.pick('knight');
check(Pets.id === 'owl', 'each hero remembers their pet: the knight has the owl again');
CharacterSelect.pick('ranger'); check(Pets.id === 'wolf', '...and the ranger the wolf');
CharacterSelect.key('Enter'); CharacterSelect.key('Enter');
check(ctx.started && ctx.player.charId === 'ranger' && ctx.companion.petId === 'wolf' && !cam.show, 'Enter on the pet step starts play (camera back to following)');
step(1);
CharacterSelect.requestMenu(); CharacterSelect.requestMenu(); step(0.2);
check(CharacterSelect.visible && Pets.id === 'wolf', 'back to character select (a new adventure): the ranger still brings the wolf');
console.log(fails ? `${fails} FAILED` : 'all passed');
