// Real gameplay signals, persistence, replay, hero controls and the fainting lifecycle.
import assert from 'node:assert/strict';
import { boot, imp } from './lib/boot.mjs';
const { game, H, step } = await boot('witch', { wake: false });
const { ctx } = await imp('core/context.js');
const { dragCamera } = await imp('systems/CameraSystem.js');
const { damageEnemy, hurtPlayer, updatePlayerVitals } = await imp('combat/damage.js');
const { Blast } = await imp('combat/hazards.js');
const { applyCharacter } = await imp('gameplay/characters.js');
const { resetCooldowns, kit } = await imp('combat/casting.js');
const { cancelAim, aim } = await imp('combat/aiming.js');
const { rebind, resetBinds } = await imp('core/keybinds.js');
const { helpText, helpHtml } = await imp('ui/help.js');
const { TUTORIAL_STEPS, HELP_TOPICS } = await imp('config/tutorial.js');
const { offsetDir } = await imp('utils/sphere.js');
const T = H.Tutorial;
const press = code => { __fire('keydown', { code }); __fire('keyup', { code }); };
assert.equal(T.step.id, 'move');
T.acknowledge(); assert.equal(T.step.id, 'move', 'practice steps cannot be advanced by acknowledgment');
const pos = H.player.up.clone(); H.player.placeAt(offsetDir(pos, 0, 5)); game.update(1 / 60);
assert.equal(T.step.id, 'move', 'teleporting without input does not count as moving');
H.player.placeAt(game.world.spawnDir); H.keys.KeyW = true; step(1.5); H.keys.KeyW = false;
assert.ok(T.state.done.includes('move'), 'actual walking teaches movement');
dragCamera(40, 10); assert.ok(T.state.done.includes('camera'));
H.Dialog.start(H.npcs[0]); assert.ok(T.state.done.includes('talk')); H.Dialog.close();
press('KeyI'); assert.ok(H.InventoryUI.isOpen && T.state.done.includes('bag')); press('Escape');
press('Digit2'); assert.equal(H.Hotbar.selected, 1); assert.ok(T.state.done.includes('hotbar'));
H.player.placeAt(offsetDir(game.world.spawnDir, 0, 24)); game.update(1 / 60); assert.ok(T.state.done.includes('trail'));
H.player.placeAt(game.world.spawnDir);
H.player.mana = 0; H.tryCast('bolt'); assert.ok(!T.state.done.includes('attack'), 'refused casts do not teach an ability');
H.player.mana = 100; H.tryCast('blink'); assert.ok(T.state.done.includes('dodge'));
assert.ok(!T.state.done.includes('attack'), 'an evasion alone does not teach the basic attack');
resetCooldowns(kit()); H.player.motion = null;
H.tryCast('bolt'); assert.ok(T.state.done.includes('attack')); resetCooldowns(kit());
const mana = H.player.mana; H.tryCast('meteor'); assert.equal(aim.id, 'meteor'); assert.equal(H.player.mana, mana);
assert.ok(T.state.done.includes('aim')); cancelAim();
const enemy = H.spawnEnemy('slime', 5); damageEnemy(enemy, 10000);
assert.ok(T.state.done.includes('fight')); assert.equal(T.step.id, 'lair');
H.TutorialUI.render(); assert.match(H.TutorialUI.root.innerHTML, /Reach level|Break the/);
T.acknowledge(); assert.equal(T.state.status, 'complete');
const xp = H.player.xp, coins = H.player.coins, bag = JSON.stringify(H.inventory.toJSON());
H.PauseMenu.open(); H.PauseMenu.onClick({ target: { closest: selector => selector === '[data-go]' ? { dataset: { go: 'tutorial' } } : null } });
assert.ok(!ctx.paused && T.step.id === 'move', 'pause replay starts a fresh guide');
assert.equal(H.player.xp, xp); assert.equal(H.player.coins, coins); assert.equal(JSON.stringify(H.inventory.toJSON()), bag);
T.skip(); assert.ok(game.saves.save().ok); assert.ok(game.saves.continue()); assert.equal(T.state.status, 'skipped');
T.start(); dragCamera(5, 0); T.remember('wood'); T.remember('smelting');
const saved = T.toJSON(); assert.ok(game.saves.save().ok); assert.ok(game.saves.continue());
assert.deepEqual(T.toJSON(), saved, 'guide progress and hints survive Continue');
const html = helpHtml(); for (const topic of HELP_TOPICS) assert.ok(html.includes(topic.title));
assert.match(html, /First finds/); assert.match(html, /Seen/);
H.JournalUI.open('help'); assert.ok(ctx.paused); H.JournalUI.close(); assert.ok(!ctx.paused);
console.log('PASS  first walk uses real actions; completion, replay, skip and persistent Help do not grant rewards');

for (const id of ['witch', 'knight', 'ranger']) {
  applyCharacter(id); T.start(); const evasion = Object.entries(kit()).find(([id]) => ['blink', 'dash', 'leap'].includes(id));
  rebind(`skill${evasion[1].slot}`, 'KeyL');
  assert.ok(helpText(TUTORIAL_STEPS.find(s => s.id === 'dodge').text).includes('L'));
  assert.ok(helpText(TUTORIAL_STEPS.find(s => s.id === 'dodge').text).includes(evasion[1].name));
  H.tryCast(evasion[0]); assert.ok(T.state.done.includes('dodge'), `${id} evasion teaches dodging`);
  H.player.clearTimers(); resetCooldowns(kit());
  H.tryCast(Object.entries(kit()).find(([, s]) => s.ult)[0]); assert.ok(aim.id); assert.ok(T.state.done.includes('aim')); cancelAim(); resetBinds();
}
console.log('PASS  all heroes teach their own evasion and ultimate, including rebound keys');

applyCharacter('witch'); H.player.invuln = 0; ctx.time = 125; T.state.lifeStartedAt = 5;
hurtPlayer(10000, H.player.pos, 0, { source: enemy }); H.TutorialUI.render();
assert.ok(H.player.dead); assert.equal(T.state.recap.source, 'Slime'); assert.equal(T.state.recap.duration, 120);
assert.match(H.TutorialUI.faint.innerHTML, /You fainted/); assert.match(H.TutorialUI.faint.innerHTML, /2m 0s/);
const recap = structuredClone(T.state.recap); hurtPlayer(100, null, 0, { source: 'another hit' }); assert.deepEqual(T.state.recap, recap);
updatePlayerVitals(0.7, game.world); const remaining = H.player.deadT;
assert.ok(game.saves.save().ok); assert.ok(game.saves.continue()); assert.ok(H.player.dead);
assert.equal(H.player.deadT, remaining); assert.deepEqual(T.state.recap, recap);
H.PauseMenu.open(); step(0.5); assert.equal(H.player.deadT, remaining, 'paused countdown stays frozen'); H.PauseMenu.close();
updatePlayerVitals(remaining + 0.01, game.world); H.TutorialUI.render();
assert.ok(!H.player.dead); assert.equal(H.TutorialUI.faint.style.display, 'none'); assert.equal(T.state.lifeStartedAt, ctx.time);
assert.equal(JSON.stringify(H.inventory.toJSON()), bag);
assert.equal(H.player.coins, coins); assert.equal(H.player.xp, xp);
H.player.invuln = 0;
const blast = new Blast({ owner: H.boss, team: 'enemy', center: H.player.up, radius: 3, delay: 1, damage: 10000, color: 0xff0000 });
blast.detonate(); blast.dispose(); assert.equal(T.state.recap.source, H.boss.def.name, 'lingering hazards name the original attacker');
updatePlayerVitals(3, game.world); H.player.invuln = 0;
hurtPlayer(10000, null); assert.equal(T.state.recap.source, 'An unknown hazard');
game.resetRun(); assert.equal(T.state.status, 'idle'); assert.deepEqual(T.state.seen, []); assert.equal(T.state.recap, null);
console.log('PASS  faint recap names the real source, survives saving, freezes on pause and clears on new adventures');
console.log('all passed');
